create table Books(
	BookId INT PRIMARY KEY AUTO_INCREMENT, 
	Title VARCHAR(300) NOT NULL, 
	Author VARCHAR(255) NOT NULL, 
	Year INT,
	BookType VARCHAR(255) NOT NULL,
	Genre VARCHAR(255) NOT NULL,
	Owner VARCHAR(255) NOT NULL,
	Status VARCHAR(255) NOT NULL,
	Location VARCHAR(255) NOT NULL,
	Language VARCHAR(255) NOT NULL
);