INSERT INTO Config (Kind, Value) VALUES
('owner', 'Luis'),
('owner', 'Cristina'),
('status', 'TBR'),
('status', 'R'),
('status', 'WIP'),
('status', 'HB'),
('location', 'Living Room'),
('location', 'Bedroom'),
('location', 'Office'),
('genre', 'Astronomy'),
('genre', 'Science Fiction'),
('genre', 'Physics'),
('genre', 'Mystery/Thriller'),
('genre', 'Philosophy'),
('genre', 'History'),
('genre', 'Gender studies'),
('genre', 'Fantasy'),
('genre', 'Adventure'),
('genre', 'Mathematics'),
('genre', 'Photography'),
('genre', 'Energy'),
('genre', 'Computer Science'),
('genre', 'Horror'),
('genre', 'Science'),
('genre', 'Paleonthology'),
('genre', 'Medicine'),
('genre', 'Environmental Studies'),
('genre', 'Chess'),
('genre', 'Biography'),
('genre', 'Childrens Books'),
('genre', 'Short stories'),
('genre', 'Ornithology'),
('genre', 'Biology'),
('genre', 'Hispanic'),
('genre', 'Economics'),
('genre', 'European'),
('genre', 'English'),
('genre', 'Poetry'),
('genre', 'Theatre'),
('genre', 'Travel'),
('genre', 'Asian'),
('genre', 'Essay'),
('genre', 'Translation'),
('genre', 'Literature'),
('genre', 'Linguistics'),
('genre', 'Cooking'),
('genre', 'American'),
('genre', 'Home'),
('genre', 'Miscellanea'),
('genre', 'Comic'),
('genre', 'Anthropology'),
('genre', 'Sport'),
('genre', 'German'),
('genre', 'Art'),
('genre', 'African'),
('genre', 'Architecture'),
('genre', 'Chemistry'),
('genre', 'Botanics'),
('genre', 'Education')
