INSERT INTO Config (Kind, Value) VALUES
('owner', 'Luis'),
('owner', 'Cristina'),
('status', 'TBR'),
('status', 'R'),
('status', 'WIP'),
('status', 'HB'),
('location', 'Office 1'),
('location', 'Office 2'),
('location', 'Office 3'),
('location', 'Office 4'),
('location', 'Office 5'),
('location', 'Office 6'),
('location', 'Office 7'),
('location', 'Office 8'),
('location', 'Office 9'),
('location', 'Office 10'),
('location', 'Office 11'),
('location', 'Office 12'),
('location', 'Balcony'),
('location', 'LR1'),
('location', 'LR4'),
('location', 'LR5'),
('location', 'LR6'),
('location', 'LR12'),
('genre', 'Astronomy'),
('genre', 'Science Fiction'),
('genre', 'Physics'),
('genre', 'Mystery/Thriller'),
('genre', 'Philosophy'),
('genre', 'History'),
('genre', 'Gender studies'),
('genre', 'Fantasy'),
('genre', 'Adventure'),
('genre', 'Mathematics'),
('genre', 'Photography'),
('genre', 'Energy'),
('genre', 'Computer Science'),
('genre', 'Horror'),
('genre', 'Science'),
('genre', 'Paleonthology'),
('genre', 'Medicine'),
('genre', 'Environmental Studies'),
('genre', 'Chess'),
('genre', 'Biography'),
('genre', 'Childrens Books'),
('genre', 'Short stories'),
('genre', 'Ornithology'),
('genre', 'Biology'),
('genre', 'Hispanic'),
('genre', 'Economics'),
('genre', 'European'),
('genre', 'English'),
('genre', 'Poetry'),
('genre', 'Theatre'),
('genre', 'Travel'),
('genre', 'Asian'),
('genre', 'Essay'),
('genre', 'Translation'),
('genre', 'Literature'),
('genre', 'Linguistics'),
('genre', 'Cooking'),
('genre', 'American'),
('genre', 'Home'),
('genre', 'Miscellanea'),
('genre', 'Comic'),
('genre', 'Anthropology'),
('genre', 'Sport'),
('genre', 'German'),
('genre', 'Art'),
('genre', 'African'),
('genre', 'Architecture'),
('genre', 'Chemistry'),
('genre', 'Botanics'),
('genre', 'Education')